[package]
name = "nt-hive2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "2.2"
displaydoc = "0.2"
bitflags = "1.3"
encoding_rs = "0.8"