[package]
name = "nt_hive2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["regdump"]
regdump = ["env_logger"]

[[bin]]
name = "regdump"
path = "src/regdump.rs"
required-features = ["regdump"]

[lib]
name = "nt_hive2"

[dependencies]
binread = "2.2"
displaydoc = "0.2"
bitflags = "1.3"
encoding_rs = "0.8"
log = "0.4"
chrono = "0.4"
env_logger = {version="0.9", optional=true}